version: '3.8'

services:
  rabbit1:
    image: rabbitmq:3.10.6-management
    hostname: rabbit
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
