services:
  rabbitmq:
    build: .
    image: rabbitmq:4.1-management-delayed
    hostname: rabbit
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
